apiVersion: v1
kind: Service
metadata:
  name: jmeter-jenkins
  labels:
    app: jmeter-jenkins
spec:
  ports:
    - port: 8080
      name: jenkins-http
      targetPort: 8080
    - port: 50000
      name: jenkins-jnlp		
      targetPort: 50000
  selector:
    run: jenkins
  type: NodePort