apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
     app: jenkins
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins
          imagePullPolicy: Never
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: jenkins-data
              mountPath: /jmeter/.jenkins
      volumes:
        - name: jenkins
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data